INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (1,'ira','Traditional IRA','IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (2,'ira','Traditional IRA','INDIVIDUAL_RETIREMENT_ACCOUNT_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (3,'ira','Simple IRA','SIMPLE');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (4,'ira','Simple IRA','SIMPLE_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (5,'ira','Roth IRA','ROTH');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (6,'ira','Roth Conversion IRA','ROTH_CONVERSION');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (7,'ira','Rollover IRA','ROLLOVER');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (8,'ira','Roth IRA','ROTH_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (9,'ira','Rollover IRA','ROLLOVER_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (10,'ira','SEP IRA','SEP');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (11,'ira','SEP IRA','SEP_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (12,'ira','Registered RSP','REGISTERED_RETIREMENT_SAVINGS_PLAN_RRSP');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (13,'ira','Spousal RSP','SPOUSAL_RETIREMENT_SAVINGS_PLAN_SRSP');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (14,'ira','Spousal IRA','SPOUSAL_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (15,'ira','Spousal Roth IRA','SPOUSAL_ROTH_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (16,'ira','SARSEP IRA','SARSEP_IRA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (28,'401k','401K','401K');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (29,'401k','401K','EMPLOYEE_RETIREMENT_ACCOUNT_401K');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (30,'401k','403B','403B');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (31,'401k','Roth','403B,ROTH_403B');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (32,'401k','403B','EMPLOYEE_RETIREMENT_SAVINGS_PLAN_403B');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (33,'401k','401A','401A');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (34,'401k','401A','MONEY_PURCHASE_RETIREMENT_PLAN_401A');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (35,'401k','Group RSP','GROUP_RETIREMENT_SAVINGS_PLAN_GRSP');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (36,'401k','Defined Contribution Plan','DEFINED_CONTRIBUTION_PLAN');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (37,'401k','Defined Benefit Plan','DEFINED_BENEFIT_PLAN');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (38,'401k','Roth 401K','EMPLOYEE_RETIREMENT_ACCOUNT_ROTH_401K');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (39,'others','Educational Savings Plan - 529','EDUCATIONAL');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (40,'others','Educational Savings Plan - 529','EDUCATIONAL_SAVINGS_PLAN_529');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (41,'others','Deferred Comp Plan - 457NQ','DEFERRED_COMPENSATION_PLAN_457');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (42,'others','Deferred Comp Plan - 409A','NONQUALIFIED_DEFERRED_COMPENSATION_PLAN_409A');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (43,'others','','HEALTH_SAVINGS_ACCOUNT_HSA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (44,'others','','COVERDELL_EDUCATION_SAVINGS_ACCOUNT_ESA');
INSERT INTO retirement_account.yodlee_supported_acctype(id, account_type, friendlyname, yodleename)VALUES (45,'others','','HEALTH_REIMBURSEMENT_ARRANGEMENT_HRA');